version: 2

multi-ecosystem-groups:
  infrastructure:
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: "pip"
    directory: "/"
    patterns: ["nginx", "redis", "postgres"]
    multi-ecosystem-group: "infrastructure"

  - package-ecosystem: "npm"
    directory: "/sf6-tracker"
    patterns: ["aws", "terraform-*"]
    multi-ecosystem-group: "infrastructure"
