version: 2

multi-ecosystem-groups:
  infrastructure:
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: "pip"
    directory: "/"
    multi-ecosystem-group: "infrastructure"

  - package-ecosystem: "npm"
    directory: "/sf6-tracker"
    multi-ecosystem-group: "infrastructure"
